let allContent = [{
        name: "Tornado of Souls",
        artist: "Megadeth",
        iconSrc: "./images/music-1-icon.jpg",
        bgcSrc: "./images/music-1.jpg",
        audio: "./songs/music-1.mp3",
    },
    {
        name: "Master of Puppets",
        artist: "Metallica",
        iconSrc: "./images/music-2-icon.jpg",
        bgcSrc: "./images/music-2.jpg",
        audio: "./songs/music-2.mp3",
    },
    {
        name: "Highway to Hell",
        artist: "AC/DC",
        iconSrc: "./images/music-3-icon.jpg",
        bgcSrc: "./images/music-3.jpg",
        audio: "./songs/music-3.mp3",
    },
    {
        name: "Speak to Me",
        artist: "Pink Floyd",
        iconSrc: "./images/music-4-icon.jpg",
        bgcSrc: "./images/music-4.jpg",
        audio: "./songs/music-10.mp3",
    },
    {
        name: "Paranoid",
        artist: "Black Sabbath",
        iconSrc: "./images/music-5-icon.jpg",
        bgcSrc: "./images/music-5.jpg",
        audio: "./songs/music-5.mp3",
    },
    {
        name: "Black Sabbath",
        artist: "Black Sabbath",
        iconSrc: "./images/music-6-icon.jpg",
        bgcSrc: "./images/music-6.jpg",
        audio: "./songs/music-6.mp3",
    },
    {
        name: "2 minutes to midnight",
        artist: "Iron Maiden",
        iconSrc: "./images/music-7-icon.jpg",
        bgcSrc: "./images/music-7.jpg",
        audio: "./songs/music-7.mp3",
    },
    {
        name: "Fear of the Dark",
        artist: "Iron Maiden",
        iconSrc: "./images/music-8-icon.jpg",
        bgcSrc: "./images/music-8.jpg",
        audio: "./songs/music-8.mp3",
    },
    {
        name: "The Trooper",
        artist: "Iron Maiden",
        iconSrc: "./images/music-9-icon.jpg",
        bgcSrc: "./images/music-9.jpg",
        audio: "./songs/music-9.mp3",
    },
    {
        name: "The Show Must Go On",
        artist: "Queen",
        iconSrc: "./images/music-10-icon.jpg",
        bgcSrc: "./images/music-10.jpg",
        audio: "./songs/music-4.mp3",
    }
];